#!/usr/bin/env python3
"""Recall and safety tests for manage_skill_links.py."""

from __future__ import annotations

import importlib.util
import json
import multiprocessing as mp
import os
import shutil
import stat
import tempfile
import time
from pathlib import Path
from types import ModuleType


SCRIPT = Path(__file__).with_name("manage_skill_links.py")


def load_manager() -> ModuleType:
    spec = importlib.util.spec_from_file_location("manage_skill_links", SCRIPT)
    if spec is None or spec.loader is None:
        raise AssertionError("could not load manage_skill_links.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


manager = load_manager()


def concurrent_apply_worker(
    repository: Path,
    targets: list[Path],
    transaction: Path,
    barrier,
    results,
) -> None:
    local_manager = load_manager()
    original_roots = local_manager.canonical_target_roots
    original_plan = local_manager.build_plan_from_canonical
    synchronized = False

    def synchronized_roots(raw_roots, canonical_repository):
        nonlocal synchronized
        roots = original_roots(raw_roots, canonical_repository)
        if not synchronized:
            synchronized = True
            barrier.wait(timeout=10)
        return roots

    def slow_plan(canonical_repository, roots, selected_skills=None):
        plan = original_plan(canonical_repository, roots, selected_skills)
        time.sleep(0.25)
        return plan

    local_manager.canonical_target_roots = synchronized_roots
    local_manager.build_plan_from_canonical = slow_plan
    started = time.monotonic()
    try:
        journal = local_manager.apply_links(repository, targets, transaction)
        results.put(("ok", transaction.name, len(journal["entries"]), time.monotonic() - started))
    except BaseException as error:
        results.put(("error", transaction.name, type(error).__name__, str(error)))


def interrupted_apply_worker(repository: Path, target: Path, transaction: Path) -> None:
    local_manager = load_manager()
    original_symlink = local_manager.os.symlink

    def interrupt_on_install(source, destination, *args, **kwargs):
        if ".holyskills-" in str(destination):
            os._exit(77)
        return original_symlink(source, destination, *args, **kwargs)

    local_manager.os.symlink = interrupt_on_install
    local_manager.apply_links(repository, [target], transaction)


def check(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def expect_error(callable_object, *args, contains: str | None = None, **kwargs):
    try:
        callable_object(*args, **kwargs)
    except manager.LinkManagerError as error:
        if contains is not None:
            check(contains.lower() in str(error).lower(), f"expected {contains!r} in {error!r}")
        return error
    raise AssertionError("expected LinkManagerError")


def make_skill(repository: Path, name: str, marker: str) -> Path:
    skill = repository / "skills" / name
    (skill / "scripts").mkdir(parents=True)
    (skill / "SKILL.md").write_text(f"---\nname: {name}\n---\n# {marker}\n", encoding="utf-8")
    (skill / "scripts" / "tool.py").write_text(f"VALUE = {marker!r}\n", encoding="utf-8")
    return skill


def copy_skill(repository: Path, target: Path, name: str) -> Path:
    destination = target / name
    shutil.copytree(repository / "skills" / name, destination)
    return destination


def assert_direct(path: Path, source: Path) -> None:
    check(path.is_symlink(), f"expected direct symlink: {path}")
    check(os.readlink(path) == str(source), f"link should name canonical source exactly: {path}")


def test_plan_apply_verify_rollback_and_unrelated(base: Path) -> None:
    repository = base / "canonical repo with spaces"
    alpha = make_skill(repository, "alpha-skill", "alpha")
    make_skill(repository, "beta-skill", "beta")
    target = base / "runtime skills with spaces"
    target.mkdir()
    copy_skill(repository, target, "alpha-skill")
    (alpha / "scripts" / "__pycache__").mkdir()
    (alpha / "scripts" / "__pycache__" / "tool.pyc").write_bytes(b"canonical generated bytes")
    (target / "alpha-skill" / "scripts" / "__pycache__").mkdir()
    (target / "alpha-skill" / "scripts" / "__pycache__" / "tool.pyc").write_bytes(b"installed generated bytes")
    unrelated = target / "third-party-skill"
    unrelated.mkdir()
    (unrelated / "owner.txt").write_text("do not touch\n", encoding="utf-8")

    plan = manager.build_plan(repository, [target])
    states = {entry["skill"]: entry["status"] for entry in plan["entries"]}
    check(states == {"alpha-skill": "copied_match", "beta-skill": "missing"}, f"unexpected plan: {states}")

    transaction = base / "transaction one"
    journal = manager.apply_links(repository, [target], transaction)
    check(journal["status"] == "applied", "apply should finish")
    assert_direct(target / "alpha-skill", alpha)
    assert_direct(target / "beta-skill", repository / "skills" / "beta-skill")
    verified = manager.build_plan(repository, [target])
    check(all(entry["status"] == "direct_link" for entry in verified["entries"]), "verify plan should be direct")
    mode = stat.S_IMODE((transaction / manager.JOURNAL_NAME).stat().st_mode)
    check(mode == 0o600, f"journal permissions should be 0600, got {oct(mode)}")
    check((unrelated / "owner.txt").read_text(encoding="utf-8") == "do not touch\n", "unrelated skill changed")

    rolled_back = manager.rollback_transaction(transaction)
    check(rolled_back["status"] == "rolled_back", "rollback should finish")
    check((target / "alpha-skill").is_dir() and not (target / "alpha-skill").is_symlink(), "copied skill not restored")
    check(not manager.lexical_exists(target / "beta-skill"), "originally missing skill should be removed")
    check((unrelated / "owner.txt").read_text(encoding="utf-8") == "do not touch\n", "rollback touched unrelated skill")
    manager.rollback_transaction(transaction)  # idempotent


def test_divergence_requires_explicit_acceptance(base: Path) -> None:
    repository = base / "divergent canonical"
    make_skill(repository, "alpha-skill", "canonical")
    target = base / "divergent target"
    target.mkdir()
    copied = copy_skill(repository, target, "alpha-skill")
    (copied / "SKILL.md").write_text("local divergent content\n", encoding="utf-8")
    plan = manager.build_plan(repository, [target])
    check(plan["entries"][0]["status"] == "divergent_directory", "divergence was not detected")
    refused = base / "refused transaction"
    expect_error(manager.apply_links, repository, [target], refused, contains="allow-noncanonical")
    check(not refused.exists(), "refused apply must not create a transaction")

    transaction = base / "accepted transaction"
    manager.apply_links(repository, [target], transaction, allow_noncanonical=True)
    assert_direct(target / "alpha-skill", repository / "skills" / "alpha-skill")
    manager.rollback_transaction(transaction)
    check((target / "alpha-skill" / "SKILL.md").read_text(encoding="utf-8") == "local divergent content\n", "divergent copy was not preserved exactly")


def test_broken_and_chained_links(base: Path) -> None:
    repository = base / "link source"
    source = make_skill(repository, "alpha-skill", "canonical")

    broken_root = base / "broken target"
    broken_root.mkdir()
    broken = broken_root / "alpha-skill"
    broken_target = base / "does not exist"
    os.symlink(str(broken_target), broken)
    plan = manager.build_plan(repository, [broken_root])
    check(plan["entries"][0]["status"] == "broken_link", "broken link was not detected")
    expect_error(manager.apply_links, repository, [broken_root], base / "broken refused")
    broken_transaction = base / "broken accepted"
    manager.apply_links(repository, [broken_root], broken_transaction, allow_noncanonical=True)
    assert_direct(broken, source)
    manager.rollback_transaction(broken_transaction)
    check(broken.is_symlink() and os.readlink(broken) == str(broken_target), "broken link was not restored")

    chain_root = base / "chained target"
    chain_root.mkdir()
    intermediate = base / "intermediate link"
    os.symlink(str(source), intermediate)
    chained = chain_root / "alpha-skill"
    os.symlink(str(intermediate), chained)
    chain_plan = manager.build_plan(repository, [chain_root])
    check(chain_plan["entries"][0]["status"] == "chained_link", "chained link was not detected")
    chain_transaction = base / "chain accepted"
    manager.apply_links(repository, [chain_root], chain_transaction, allow_noncanonical=True)
    assert_direct(chained, source)
    manager.rollback_transaction(chain_transaction)
    check(chained.is_symlink() and os.readlink(chained) == str(intermediate), "chain was not restored")


def test_noncanonical_links_and_unexpected_objects(base: Path) -> None:
    repository = base / "noncanonical source"
    source = make_skill(repository, "alpha-skill", "canonical")

    relative_root = base / "relative-link target"
    relative_root.mkdir()
    relative = os.path.relpath(source, relative_root)
    os.symlink(relative, relative_root / "alpha-skill")
    plan = manager.build_plan(repository, [relative_root])
    check(plan["entries"][0]["status"] == "noncanonical_link", "relative legacy link was not detected")
    transaction = base / "relative transaction"
    manager.apply_links(repository, [relative_root], transaction, allow_noncanonical=True)
    assert_direct(relative_root / "alpha-skill", source)
    manager.rollback_transaction(transaction)
    check(os.readlink(relative_root / "alpha-skill") == relative, "relative legacy link was not restored")

    file_root = base / "unexpected file target"
    file_root.mkdir()
    unexpected_file = file_root / "alpha-skill"
    unexpected_file.write_text("locally owned file\n", encoding="utf-8")
    file_plan = manager.build_plan(repository, [file_root])
    check(file_plan["entries"][0]["status"] == "unexpected_file", "unexpected file was not detected")
    expect_error(manager.apply_links, repository, [file_root], base / "unexpected file refused")
    file_transaction = base / "unexpected file accepted"
    manager.apply_links(repository, [file_root], file_transaction, allow_noncanonical=True)
    manager.rollback_transaction(file_transaction)
    check(unexpected_file.read_text(encoding="utf-8") == "locally owned file\n", "unexpected file was not restored")

    if hasattr(os, "mkfifo"):
        object_root = base / "unexpected object target"
        object_root.mkdir()
        fifo = object_root / "alpha-skill"
        os.mkfifo(fifo)
        object_plan = manager.build_plan(repository, [object_root])
        check(object_plan["entries"][0]["status"] == "unexpected_object", "unexpected filesystem object was not detected")
        expect_error(manager.apply_links, repository, [object_root], base / "unexpected object refused")
        object_transaction = base / "unexpected object accepted"
        manager.apply_links(repository, [object_root], object_transaction, allow_noncanonical=True)
        assert_direct(fifo, source)
        manager.rollback_transaction(object_transaction)
        check(stat.S_ISFIFO(fifo.lstat().st_mode), "FIFO was not restored exactly")

        tamper_transaction = base / "unexpected object tamper"
        manager.apply_links(repository, [object_root], tamper_transaction, allow_noncanonical=True)
        backup = tamper_transaction / "backups" / "root-0" / "alpha-skill"
        backup.unlink()
        backup.write_text("not the recorded FIFO\n", encoding="utf-8")
        expect_error(manager.rollback_transaction, tamper_transaction, contains="no longer matches")
        assert_direct(fifo, source)


def test_partial_failure_rolls_back_everything(base: Path) -> None:
    repository = base / "partial canonical"
    make_skill(repository, "alpha-skill", "alpha")
    make_skill(repository, "beta-skill", "beta")
    target = base / "partial target"
    target.mkdir()
    copy_skill(repository, target, "alpha-skill")
    copy_skill(repository, target, "beta-skill")
    before = {name: manager.tree_digest(target / name) for name in ("alpha-skill", "beta-skill")}
    transaction = base / "partial transaction"
    expect_error(manager.apply_links, repository, [target], transaction, failure_after=1, contains="rolled back")
    journal = json.loads((transaction / manager.JOURNAL_NAME).read_text(encoding="utf-8"))
    check(journal["status"] == "rolled_back", "failed apply should leave a rolled-back journal")
    for name in before:
        check((target / name).is_dir() and not (target / name).is_symlink(), f"{name} remained linked")
        check(manager.tree_digest(target / name) == before[name], f"{name} changed after rollback")
    expect_error(manager.apply_links, repository, [target], transaction, contains="already exists")


def test_rollback_refuses_post_apply_changes(base: Path) -> None:
    repository = base / "rollback canonical"
    make_skill(repository, "alpha-skill", "alpha")
    make_skill(repository, "beta-skill", "beta")
    target = base / "rollback target"
    target.mkdir()
    copy_skill(repository, target, "alpha-skill")
    copy_skill(repository, target, "beta-skill")
    transaction = base / "rollback transaction"
    manager.apply_links(repository, [target], transaction)
    (target / "alpha-skill").unlink()
    (target / "alpha-skill").mkdir()
    (target / "alpha-skill" / "new.txt").write_text("post apply\n", encoding="utf-8")
    expect_error(manager.rollback_transaction, transaction, contains="post-apply change")
    check((target / "beta-skill").is_symlink(), "rollback mutated another skill before completing preflight")
    manager.rollback_transaction(transaction, force=True)
    check((target / "alpha-skill" / "SKILL.md").is_file(), "force rollback did not restore original")
    check((target / "beta-skill" / "SKILL.md").is_file() and not (target / "beta-skill").is_symlink(), "force rollback did not restore all skills")


def test_concurrent_applies_serialize_and_replan(base: Path) -> None:
    repository = base / "concurrent canonical"
    make_skill(repository, "alpha-skill", "alpha")
    make_skill(repository, "beta-skill", "beta")
    targets = [base / "concurrent target one", base / "concurrent target two"]
    for target in targets:
        target.mkdir()
        copy_skill(repository, target, "alpha-skill")
        copy_skill(repository, target, "beta-skill")
    unrelated = targets[0] / "unrelated-skill"
    unrelated.mkdir()
    (unrelated / "owner.txt").write_text("preserve me\n", encoding="utf-8")

    context = mp.get_context("fork")
    barrier = context.Barrier(2)
    results = context.Queue()
    transactions = [base / "concurrent tx one", base / "concurrent tx two"]
    target_orders = [targets, list(reversed(targets))]
    processes = [
        context.Process(
            target=concurrent_apply_worker,
            args=(repository, target_orders[index], transaction, barrier, results),
        )
        for index, transaction in enumerate(transactions)
    ]
    for process in processes:
        process.start()
    for process in processes:
        process.join(15)
        check(not process.is_alive(), "concurrent apply deadlocked")
        check(process.exitcode == 0, f"concurrent apply worker exited {process.exitcode}")

    outcomes = [results.get(timeout=2) for _ in processes]
    check(all(outcome[0] == "ok" for outcome in outcomes), f"concurrent apply failed: {outcomes}")
    entry_counts = sorted(outcome[2] for outcome in outcomes)
    check(entry_counts == [0, 4], f"second apply did not replan direct links: {outcomes}")
    durations = sorted(outcome[3] for outcome in outcomes)
    check(durations[-1] >= 0.40, f"second apply did not wait for the root lock: {outcomes}")
    for target in targets:
        assert_direct(target / "alpha-skill", repository / "skills" / "alpha-skill")
        assert_direct(target / "beta-skill", repository / "skills" / "beta-skill")
    check((unrelated / "owner.txt").read_text(encoding="utf-8") == "preserve me\n", "concurrent apply touched unrelated entry")

    journals = [json.loads((transaction / manager.JOURNAL_NAME).read_text(encoding="utf-8")) for transaction in transactions]
    owning_transaction = transactions[[len(journal["entries"]) for journal in journals].index(4)]
    manager.rollback_transaction(owning_transaction)
    for target in targets:
        check((target / "alpha-skill").is_dir() and not (target / "alpha-skill").is_symlink(), "serialized rollback lost alpha")
        check((target / "beta-skill").is_dir() and not (target / "beta-skill").is_symlink(), "serialized rollback lost beta")


def test_post_plan_change_is_preserved_before_move(base: Path) -> None:
    repository = base / "post-plan canonical"
    make_skill(repository, "alpha-skill", "alpha")
    target = base / "post-plan target"
    target.mkdir()
    copy_skill(repository, target, "alpha-skill")
    original_prepare = manager.prepare_transaction

    def replace_after_plan(path, canonical_repository, roots):
        destination = target / "alpha-skill"
        shutil.rmtree(destination)
        destination.mkdir()
        (destination / "valuable-new-state.txt").write_text("created after planning\n", encoding="utf-8")
        return original_prepare(path, canonical_repository, roots)

    manager.prepare_transaction = replace_after_plan
    transaction = base / "post-plan transaction"
    try:
        expect_error(manager.apply_links, repository, [target], transaction, contains="changed after planning")
    finally:
        manager.prepare_transaction = original_prepare
    destination = target / "alpha-skill"
    check(destination.is_dir() and not destination.is_symlink(), "post-plan replacement was moved or linked")
    check((destination / "valuable-new-state.txt").read_text(encoding="utf-8") == "created after planning\n", "post-plan content was not preserved")
    check(not manager.lexical_exists(transaction / "backups" / "root-0" / "alpha-skill"), "post-plan replacement was moved into backup")
    journal = json.loads((transaction / manager.JOURNAL_NAME).read_text(encoding="utf-8"))
    check(journal["status"] == "rolled_back", "preserved post-plan change should leave a closed transaction")


def test_unrelated_post_plan_change_is_not_a_false_positive(base: Path) -> None:
    repository = base / "unrelated-change canonical"
    make_skill(repository, "alpha-skill", "alpha")
    target = base / "unrelated-change target"
    target.mkdir()
    copy_skill(repository, target, "alpha-skill")
    unrelated = target / "third-party-skill"
    unrelated.mkdir()
    original_prepare = manager.prepare_transaction

    def change_unrelated_after_plan(path, canonical_repository, roots):
        (unrelated / "new-owner-state.txt").write_text("unrelated concurrent change\n", encoding="utf-8")
        return original_prepare(path, canonical_repository, roots)

    manager.prepare_transaction = change_unrelated_after_plan
    transaction = base / "unrelated-change transaction"
    try:
        journal = manager.apply_links(repository, [target], transaction)
    finally:
        manager.prepare_transaction = original_prepare
    check(journal["status"] == "applied", "unrelated post-plan change should not block apply")
    assert_direct(target / "alpha-skill", repository / "skills" / "alpha-skill")
    check((unrelated / "new-owner-state.txt").read_text(encoding="utf-8") == "unrelated concurrent change\n", "unrelated change was touched")
    manager.rollback_transaction(transaction)
    check((unrelated / "new-owner-state.txt").is_file(), "rollback touched unrelated concurrent change")


def test_target_root_replacement_cannot_redirect_mutation(base: Path) -> None:
    repository = base / "root-swap canonical"
    make_skill(repository, "alpha-skill", "alpha")
    target = base / "selected target"
    outside = base / "outside selected target"
    target.mkdir()
    outside.mkdir()
    copy_skill(repository, target, "alpha-skill")
    copy_skill(repository, outside, "alpha-skill")
    original_target = base / "original selected target"
    original_prepare = manager.prepare_transaction

    def redirect_after_plan(path, canonical_repository, roots):
        target.rename(original_target)
        os.symlink(outside, target)
        return original_prepare(path, canonical_repository, roots)

    manager.prepare_transaction = redirect_after_plan
    try:
        expect_error(
            manager.apply_links,
            repository,
            [target],
            base / "root-swap transaction",
            contains="target root path was replaced",
        )
    finally:
        manager.prepare_transaction = original_prepare
    check((outside / "alpha-skill").is_dir() and not (outside / "alpha-skill").is_symlink(), "mutation escaped through a replaced target root")
    check((original_target / "alpha-skill").is_dir(), "original selected root was mutated after its path moved")


def test_rollback_refuses_replaced_root_and_recovers_after_restore(base: Path) -> None:
    repository = base / "rollback-root canonical"
    make_skill(repository, "alpha-skill", "alpha")
    target = base / "rollback selected target"
    outside = base / "rollback outside target"
    target.mkdir()
    outside.mkdir()
    copy_skill(repository, target, "alpha-skill")
    copy_skill(repository, outside, "alpha-skill")
    transaction = base / "rollback-root transaction"
    manager.apply_links(repository, [target], transaction)
    moved_target = base / "rollback moved selected target"
    target.rename(moved_target)
    os.symlink(outside, target)
    expect_error(manager.rollback_transaction, transaction, contains="safely open target root")
    check((outside / "alpha-skill").is_dir() and not (outside / "alpha-skill").is_symlink(), "rollback escaped through replacement root")
    target.unlink()
    moved_target.rename(target)
    manager.rollback_transaction(transaction)
    check((target / "alpha-skill").is_dir() and not (target / "alpha-skill").is_symlink(), "rollback did not recover after root path restoration")


def test_abrupt_interruption_can_be_rolled_back(base: Path) -> None:
    repository = base / "interruption canonical"
    make_skill(repository, "alpha-skill", "alpha")
    target = base / "interruption target"
    target.mkdir()
    copied = copy_skill(repository, target, "alpha-skill")
    before = manager.tree_digest(copied)
    transaction = base / "interruption transaction"
    context = mp.get_context("fork")
    process = context.Process(target=interrupted_apply_worker, args=(repository, target, transaction))
    process.start()
    process.join(10)
    check(not process.is_alive(), "interrupted worker did not exit")
    check(process.exitcode == 77, f"expected abrupt exit 77, got {process.exitcode}")
    interrupted = json.loads((transaction / manager.JOURNAL_NAME).read_text(encoding="utf-8"))
    check(interrupted["status"] == "applying", f"unexpected interrupted status: {interrupted['status']}")
    check(interrupted["entries"][0]["stage"] == "backup_moved", "interruption fixture did not stop after durable backup")
    manager.rollback_transaction(transaction)
    restored = target / "alpha-skill"
    check(restored.is_dir() and not restored.is_symlink(), "interruption rollback did not restore copied skill")
    check(manager.tree_digest(restored) == before, "interruption rollback changed copied skill")


def test_input_guards(base: Path) -> None:
    repository = base / "guard canonical"
    make_skill(repository, "alpha-skill", "alpha")
    target = base / "guard target"
    target.mkdir()
    expect_error(manager.build_plan, repository, [], contains="target-root")
    expect_error(manager.build_plan, repository, [Path("relative")], contains="absolute")
    expect_error(manager.build_plan, repository, [repository / "skills"], contains="outside")
    root_link = base / "root link"
    os.symlink(str(target), root_link)
    expect_error(manager.build_plan, repository, [root_link], contains="real directory")
    nested = target / "nested runtime"
    nested.mkdir()
    expect_error(manager.build_plan, repository, [target, nested], contains="must not be nested")


def main() -> int:
    base = Path(tempfile.mkdtemp(prefix="holy skills link self test "))
    try:
        test_plan_apply_verify_rollback_and_unrelated(base)
        test_divergence_requires_explicit_acceptance(base)
        test_broken_and_chained_links(base)
        test_noncanonical_links_and_unexpected_objects(base)
        test_partial_failure_rolls_back_everything(base)
        test_rollback_refuses_post_apply_changes(base)
        test_concurrent_applies_serialize_and_replan(base)
        test_post_plan_change_is_preserved_before_move(base)
        test_unrelated_post_plan_change_is_not_a_false_positive(base)
        test_target_root_replacement_cannot_redirect_mutation(base)
        test_rollback_refuses_replaced_root_and_recovers_after_restore(base)
        test_abrupt_interruption_can_be_rolled_back(base)
        test_input_guards(base)
        print("skill link manager self-test ok")
        return 0
    finally:
        shutil.rmtree(base, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
